### PR TITLE
- Fixe, Concert and Future sites added

### PR DESCRIPTION
**Pull request by f-to**
- Fixed problem with some videowith VOF as versionShortLibelle
- Addded Concert and Future sites as well

### CODE REVIEW

**Comment by iNaD** [comment]
Hi,

thanks for the contribution. My Synology is currently "under maintenance", so it'll tke some time until I can review your changes.

**Comment by f-to** [comment]
Hi,

You are welcome !

**Comment by iNaD** [comment]
Thanks for the linux buildscript. I hope that there's some spare time soon to review your commits :)

**Comment by f-to** [comment]
Feel free to correct any weird things I've done when you have spare time :)

Also I'm adding theoperaplatform.eu to the module as it's the same as
arte.tv websites.

Cheers

**Comment by iNaD** [comment]
Hi Flor27,

I'm currently reviewing your changes. I will take your changes as a start and rewrite the provider a little bit, because I'm not fully happy how it's currently structured (especially with all the new cases caused by The Opera Platform etc.). I hope that I'll finish it today.

**Comment by iNaD** [comment]
@Flor27 let me know if the current state of the master branch works with the download station, my Syno is still dead.

[artemediathek.zip](https://github.com/iNaD/download-station-artemediathek/files/411093/artemediathek.zip)

**Comment by f-to** [comment]
Hello Daniel,

I Will within a week or so!

Best regards
Florent

**Pull request closed without merging**
